# Generated by Django 5.2.16 on 2026-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_customer_product_rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('product', 'customer_id'), name='unique_customer_product_rating'),
        ),
    ]
