# Generated by Django 5.2.16 on 2026-07-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_rating_unique_customer_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_customer_product_rating',
        ),
    ]
