"""
API URL Configuration.

All endpoints are versioned under /api/v1/ for future compatibility.
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

# Router auto-generates URL patterns for ViewSets
router = DefaultRouter()
router.register(r'products', views.ProductViewSet, basename='product')
router.register(r'categories', views.CategoryViewSet, basename='category')
router.register(r'orders', views.OrderViewSet, basename='order')

urlpatterns = [
    # ViewSet routes (auto-generated by router)
    path('', include(router.urls)),

    # Auth
    path('auth/register/', views.RegisterView.as_view(), name='api-register'),
    path('auth/login/', TokenObtainPairView.as_view(), name='api-token-obtain'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='api-token-refresh'),
    path('auth/profile/', views.UserProfileView.as_view(), name='api-profile'),
]
